news: add osbuild-composer 13 release announcement
osbuild/legacy-website pull request #18
Opened 2020-05-29 05:15 UTC by ondrejbudai

2020-05-29 05:59 UTC, dvdhrm requested changes

2020-05-29 05:59 UTC, dvdhrm commented on _collections/_news/2020-05-29-release-osbuild-composer-13.md
> +Yesterday, we release version 13 of *osbuild-composer*. We are very proud of
`release` -> `released`

2020-05-29 05:59 UTC, dvdhrm commented on _collections/_news/2020-05-29-release-osbuild-composer-13.md
> +for RHEL 8 and dropping the ability to build Fedora 30 distribution and
`distribution` -> `distributions` (or just drop `distribution` entirely)

2020-05-29 20:14 UTC, ondrejbudai commented
Fixed both issues

2020-05-30 07:55 UTC, dvdhrm approved these changes

2020-05-30 07:55 UTC, merged